# serverless.yml
service: extract-keyphrases
provider:
  name: kubeless
  runtime: python3.8
  timeout: 120 # optional, in seconds, default is 180

plugins:
  - serverless-kubeless

functions:
  extract-keyphrases:
    handler: handler.extract_keyphrases
    description: Extracts keyphrases from a given (pdf) file s an annotation
    port: 8080 # optional, this is the default value
    path: /extract-keyphrases
    environment:
      SENTENCE_TRANSFORMERS_HOME: /tmp/ # This folder will be used to download the model