apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
 name: keyphrase-extractor
 namespace: default
 label:
   created-by: kubeless
   function: scraper
spec:
 runtime: python3.8
 timeout: "180"
 handler: handler.extract_keyphrases
 deps: ""
 # Checksum is included for security purposes and ensures our files are not tampered with.
 # The checksum can be calculated via: openssl dgst -sha256 ./package.zip
 checksum: 24f5593edf2de6ed85bac9fe24cd626a932c8609b6eb060d6de10c3dd484db19
 function-content-type: url+zip
 function: https://github.com/Ask-Waldo/ask-waldo-keyphrase-extraction-serverless/blob/master/zip/package.zip?raw=true